### ISSUE TITLE
A more indepth documentation

### ISSUE THREAD

**Issue by FrederikLauber** [conqp/wgmgr#1]
Hello,

I am at the moment looking for a easy way to manage multiple peers in a wireguard vpn setup. 
From what I read, this tool should be ideal for this but unfortunately, there is virtually 0 documentation on how to use it. 

Even just a short tutorial on setting up an server would suffice. Just wanted to ask before I start diving into the code to figure out what I need to do to make this work.
Cheers,
Frederik

**Comment by conqp** [comment]
Since `wgmgr` has never seen much attention, I never considered writing extensive documentation for it.
The setup should be straightforward as with all python  software shipping a `setup.py`:

    python3 setup.py install

Contrary to [wgtools](https://github.com/conqp/wgtools), `wgmgr` is not inteded to be used solely as a library (though you still might do that). It's purpose is to provide the eponymous CLI program `wgmgr`.
You can, after you have installed it, always find a brief documentation using

    wgmgr -h

I might one day write a man page for this, but I currently don't have the time to do so.
Regarding the source code, all classes and functions are documented with docstrings. So you can always generate source code documentation for yourself using e.g. [pydoc](https://docs.python.org/3/library/pydoc.html).

**Comment by FrederikLauber** [comment]
Hi,

I tried to make sense out of the the output of wgmgr -h but am failing hard.
I guess you first have to run init to configure the wireguard interface but the paramters are not self explanatory, the error messages are not helpful and even once I had a wireguard itnerface, adding a user did not seme to do anything. So I bet I am doing something wrong here. Do I have to run this as root or is it enough to call it with sudo? What happenes if a wireguard interface is already configured when I call the init? It seems to ahve regonized the alredy existing one updating the network but did not add users. Do I have to do something to have a permament configuration? 

It doesn't need to be exesive documentation just a "here is what you do on the server for setup -> 1-2 commands, add user like this, data is stored here and here".

**Comment by conqp** [comment]
I think you have a completely wrong idea of what wgmgr is about.
It's primarily about managing a WireGuard PKI for an OpenVPN-like Client / Server setup.
While it can generate configuration files for systemd-networkd, which might require root permissions in order to write the files, it is not intended to be generally run as root. On the contrary, it is a user space tool to manage networks, keys, peers etc.
With

    wgmgr init ...

you initialize a (new) PKI. This by itself will not at all influence any existing network device configuration.
You just setup your PKI.

If you setup your PKI to your specs, you _can_ generate device configurations from it using

    wgmgr client dump <name> -o /path/to/file

or

    wgmgr server dump -o /path/to/file

respectively.

Example workflow:

```
$ wgmgr init MyPrivateNetwork "Some description" 10.8.0.0/24 10.8.0.1 my.server.com:51820
$ wgmgr client add r9lJ1vbl0zTwZ8MiwefNAETqEPcOKNKu2Vzm+lU8pwU= -n MyFirstClient
$ wgmgr server dump
[NetDev]
Name = MyPrivateNetwork
Kind = wireguard
Description = Some description

[WireGuard]
ListenPort = 51820
PrivateKey = cFA2i9zd94K9iIstoxg790BYJx1lKK1ok1tjQQKZcGQ=

[WireGuardPeer]
PublicKey = r9lJ1vbl0zTwZ8MiwefNAETqEPcOKNKu2Vzm+lU8pwU=
AllowedIPs = 10.8.0.2/32
$ wgmgr client dump MyFirstClient
[Interface]
PrivateKey = <your private key>
Address = 10.8.0.2/32

[Peer]
PublicKey = avF6+5FS1/8fTEoEA7tCF0uxWbJb7CtQjfDJl73DWyI=
AllowedIPs = 10.8.0.0/24
Endpoint = my.server.com:51820
```
